### ISSUE TITLE
Use signalfd/eventfd/timerfd when available

### ISSUE THREAD

**Issue by gdamjan** [dabeaz/curio#24] opened 2015-12-08 18:58 UTC
These are advanced linux system calls that make file descriptors instead of the classic Posix calls: signal, pipes/sockets and sleep/select(with timeout), thus making some operations either more performant (eventfd, timerfd), or more correct (signalfd).

There are already some implementations of these on pypi. 

Discuss! :)

**Comment by dabeaz** [comment] 2015-12-21 10:50
Would need to see some concrete examples.   How would these be used in curio?

**Comment by kdart** [comment] 2016-01-07 07:24
I wrote a [wrapper for timerfd]( https://github.com/kdart/pycopia3/blob/master/utils/pycopia.timers.pyx#L171) that can be used in an async event loop. An example of it's use can be found in my [sequencer module](https://github.com/kdart/pycopia3/blob/master/core/pycopia/OS/Linux/sequencer.py#L30).  It uses my own async loop, but I'm sure it could be adapted to curio.  In fact I like curio better so I may port my stuff to it. :)

**Comment by Blitzworks** [comment] 2017-01-06 11:14
I have a wrapper for timerfd, eventfd, signalfd and inotify that allow you to get directly at the low level stuff (fd's) as well as provide a high level interface. Exceptions are standardized and there are plenty of docstring examples

https://pypi.python.org/pypi/butter/0.12.2

Example usage of timerfd:
http://blitz.works/butter/file/76498f5a3174/butter/timerfd.py#l18

signalfd can be a bit counter intuitive as the signalfd has a separate signal mask to the normal unix signals and if you wish to have delivery only via signalfd you need to ensure that the appropriate signals are set to not fire via the standard mechanisms (signal module)

none of these will make a program more performant, but they may make it slightly 'cleaner' at the cost of moving the complexity to a 3rd party library, the timerfd however can be useful as an interval timer to time how long something has occurred for. I covered this briefly at http://pocketnix.org/posts/Tidbits%3A%20TimerFD%20as%20an%20interval%20timer

one bug was reported in the python 3 support/setup.py but that should be fixed in the next day or so

**Comment by njsmith** [comment] 2017-01-06 20:26
I guess the problem is that adding new cleaner code doesn't actually make
the overall program cleaner, if you have to keep all the old code as well
to handle non-Linux systems.

**Comment by dabeaz** [comment] 2018-11-18 16:30
The core Curio kernel loop is pretty minimal.   However, if these features use standard Linux file descriptors, I suspect that they could be supported at the Curio "user-level" so-to-speak.  I'd suggest making a separate package for it rather that having it in the Curio core.

**Closed by dabeaz** 2018-11-18 16:30 UTC
