### ISSUE TITLE
timeout_after doesn't work with subprocess.run?

### ISSUE THREAD

**Issue by tutufan** [dabeaz/curio#141] opened 2016-12-16 23:54 UTC
Newbie here trying to use curio.subprocess.run inside of a timeout_after.  Strangely, it doesn't seem to work--the timeout doesn't happen--but seems to work if I use curio.sleep instead.

Here's an example.  (Might have syntax errors since I'm having to type this in at work.)

```python
import curio
import curio.subprocess

async def subproc(n):
    try:
        async with curio.timeout_after(3):
            # r = await curio.sleep(n)
            r = await curio.subprocess.run(['sleep', str(n)], stdin=curio.subprocess.DEVNULL, stdout=curio.subprocess.PIPE, check=True)
    except curio.TaskTimeout:
        r = "timeout {}".format(n)
    return r

async def subproc_test():
    tasks = [await curio.spawn(subproc(n)) for n in range(5)]
    async for task in curio.wait(tasks):
        try:
            r = await task.join()
            print("task end", r, flush=True)
        except curio.TaskError as e:
            print("task failed ({!r})".format(e), flush=True)

if __name__ == '__main__':
    curio.run(subproc_test())
```

I feel I must be missing something.  I could use the timeout parameter of subprocess.run, but that doesn't seem very curionic.  Cheers!

**Comment by dabeaz** [comment] 2016-12-17 20:57
Interesting.   Looked into the code,   if no timeout is given to `subprocess.run()`, it ends up disabling all timeouts!  This is clearly a bug.   However, let me ask a higher-level question....

Maybe the `subprocess.run()` and related functionality should NOT take an explicit timeout parameter.  This would be consistent with the rest of curio where no functions normally take a explicit timeout.   The only reason the `subprocess` related functions have them is that I was trying to emulate the subprocess API.   This would break from that, but maybe that's okay.  

Thoughts?

**Comment by tutufan** [comment] 2016-12-17 21:04
For myself, I would always use the curio timeout functions, rather than the subprocess timeout parameter, unless there's some subtle advantage that I'm missing that would only be possible with the latter.  I've no objection to having the parameter, but it'd seem awkward to me to use it.

**Comment by dabeaz** [comment] 2016-12-17 21:16
Honestly, the only benefit that I can see here is that that curio subprocess module very closely models the actual subprocess module API, even using the same exceptions.   For example, a timeout error actually raises `subprocess.TimeoutExpired`.  This isn't even a Curio exception.  Frankly it's kind of weird.

I'm kind of inclined to the get rid of timeout option entirely and make people use the `timeout_after()` function instead.

**Comment by tutufan** [comment] 2016-12-17 21:39
That seems reasonable to me.  And there's something to be said for not having two slightly different ways to achieve the same effect.

**Comment by imrn** [comment] 2016-12-17 21:53
> Maybe the `subprocess.run()` and related functionality should NOT take an
> explicit timeout parameter.  This would be consistent with the rest of curio
> where no functions normally take a explicit timeout.   The only reason the
> `subprocess` related functions have them is that I was trying to emulate the
> subprocess API.   This would break from that, but maybe that's okay.
> Thoughts?

Given curio promotes timeoutafter/ignoreafter async calls and
timeout contextmanagers it makes sense.

+ Generally we kill or terminate a timedout process.
Underlying subprocess actually has that api.
Is it safe to use use curiosubprocess._popen.kill/term/send/signal()?
Or should curio have its own wrapper calls?

++ Can we have a good example for nested timeout in documentation?

**Comment by dabeaz** [comment] 2016-12-17 22:06
The curio subprocess functions already kill the underlying subprocess on timeout.  In this case, the timeout wasn't occurring because the `timeout_after()` function was being passed `None` (the default timeout on subprocess functions) and it was suppressing the timeout.    This subprocess module was one of the first things done with curio and predates the `timeout_after()` function actually.  So, it's a bit weird.  I'm going to tweak it.

On nested timeouts, I'm pretty sure there is a documentation section about that already.  I know there is a section about what happens when you nest timeouts and how the exceptions get handled.

**Comment by imrn** [comment] 2016-12-17 22:19
On 12/18/16, David Beazley <notifications@github.com> wrote:
> The curio subprocess functions already kill the underlying subprocess on
> timeout.

Does cancelling the below task kill it? Anyway, curio
user may need a way to kill/term a subprocess
on conditions other than a timeout.

```python
    async def wait(self, timeout=None):
        async def waiter():
            while True:
                retcode = self._popen.poll()
                if retcode is not None:
                    return retcode
                await sleep(0.0005)
        task = await spawn(waiter())
        try:
            return await timeout_after(timeout, task.join())
        except TaskTimeout:
            await task.cancel()
            raise TimeoutExpired(self.args, timeout) from None
```

> On nested timeouts, I'm pretty sure there is a documentation section about
> that already.  I know there is a section about what happens when you nest
> timeouts and how the exceptions get handled.

Yes there is. But without a 'nested' example.

**Comment by imrn** [comment] 2016-12-17 22:37
> On 12/18/16, David Beazley <notifications@github.com> wrote:
>> The curio subprocess functions already kill the underlying subprocess on
>> timeout.

+++ Killing a process on a timeout may or may not be good idea.
I think there can be no default behaviour. Let's leave it to the user.

**Comment by tutufan** [comment] 2016-12-17 23:06
For myself, I generally want the underlying process to get the SIGTERM on timeout.  Just letting it run free sounds like a bad idea, except in a few rare circumstances.  If that were going to happen, the process should be daemonized from the start.  (In fact, it might be useful to have an option for the subprocess to get a SIGKILL instead, though this could be implemented by the caller after the timeout.)

**Comment by imrn** [comment] 2016-12-18 16:20
Not killing the process would not mean letting it go uncontrolled.
You may need to do someother things before killing it, even
a timeout may not mean a zombie process. It may be the nature
of process. You may do other things and retry waiting, reading, writing,
or just kill it, etc, etc..

Furthermore if we make the switch, how will you tell wait() to kill
or not to kill process with just this:

async with timeout_after(5)
    await proc.wait()

You have to define your definite intent while handling
the timeout exception. Yes, this makes all things alot longer
than just this:

await proc.wait(timeout=5, kill_on_timeout=False/True).

Now what will we do? :)

May be below suggestion helps:
1) If Popen is used as Context Manager everything should be
cleaned up upon exit. (Which is probably the case. Let's check.)
2) If it is not used as a CM no default action should be performed.
3) To mirror sync subprocess add kill()/term()/sendsignal(), etc functions
to the api.
4) For the sake of consistency continue with removed timeouts from
all functions. Unfortunately this will remove shortcuts.. :(

Any comments on this?

**Comment by imrn** [comment] 2016-12-18 16:40
Dave: Just to double check: Can you confirm such a code
does not forge an already closed the process at the boundry
of timeout OR cause lost bytes on a socket/stream OR any similar
things?

try:
    async with timeout_after(5)
        await proc.wait()
        r = await stream.read()
except:
    await proc.wait()
    r = await stream.read()

**Comment by njsmith** [comment] 2016-12-18 16:59
FWIW, my expectations would be:

* Timeout/cancellation in subprocess.run: the underlying process gets
killed. Ideally with SIGTERM + wait a bit + SIGKILL if necessary? So we
might need some option to run() to adjust the killing strategy (E.g. how
long to wait before SIGKILL)

* Timeout/cancellation in popen.wait(): the wait is cancelled, but the
process is *not* killed.

And popen objects should certainly be supported as context managers, if
they aren't already. I guess with the same configurability for how the
process should be killed on exit.

**Comment by imrn** [comment] 2016-12-18 17:09
On 12/18/16, Nathaniel J. Smith <notifications@github.com> wrote:
> And popen objects should certainly be supported as context managers, if
> they aren't already.

They are already..

**Comment by imrn** [comment] 2016-12-18 17:09
>4) For the sake of consistency continue with removed timeouts from
>all functions. Unfortunately this will remove shortcuts.. :(

OR should we support both: That is:
- Signatures of all sync functions with timeouts are supported
as optional arguments. That is, they'll all contain their
timeout_after call/CM in their curio wrapper.

- If optional timeout argument is absent then everything
will be as it is today.

Is this a good idea?

**Comment by dabeaz** [comment] 2016-12-20 23:42
Just a note that I'm thinking this subprocess submodule probably needs some major work.  Will get to it soon.   

One thing I've been contemplating is whether or not timeout_after() should have a mode of simply using the existing timeout setting (if any).   The main problem in the current implementation is that the subprocess functions inadvertently disable the timeout entirely if none is specified as an option. For example::

     def run(..., timeout=None, ...):
            with timeout_after(timeout):   # Disables timeouts entirely by default
                   ...

It would make it easier to write the code if a suitable default value could be used that simply preserved the existing timeout setting if none was given otherwise.  Maybe 0 could indicate this::

    def run(..., timeout=0, ...):
           with timeout_after(timeout):    # Use existing timeout setting by default

Again, requires some thought.

**Comment by njsmith** [comment] 2016-12-21 00:05
IMO we should deprecate `timeout_after(None)` in favor of `defer_cancellation`? (I forget whether I made `defer_cancellation` also block timeouts yet, but if I haven't then I should ;-).) Then we could have `timeout_after(None)` just be a no-op.

**Comment by dabeaz** [comment] 2016-12-21 00:23
I'd  be open to removing `timeout_after(None)` or repurposing it.  In looking at this bug, I realized I might have to write code like this::

    def run(..., timeout=None, ...):
        if timeout is None:
                # Do whatever 
                ...
        else:
              with timeout_after(timeout):
                   # Do whatever
                   ...

Frankly, that's pretty weird.  I don't want to have two branches of code like that.   I'm still thinking about just eliminating the timeout option altogether.   The function could still catch cancellation requests (including timeouts) and take steps to kill the subprocess in a clean way.

**Comment by njsmith** [comment] 2016-12-21 01:08
Yeah, removing the timeout argument also seems like a good idea to me :-).
Curio's socket API dropped the timeout-related functions and arguments,
after all...

**Comment by imrn** [comment] 2016-12-21 06:56
On 12/21/16, David Beazley <notifications@github.com> wrote:
> Frankly, that's pretty weird.  I don't want to have two branches of code
> like that.   I'm still thinking about just eliminating the timeout option
> altogether.

While it is a good and general thing for consistency,
it causes "exceptions" spread all over the user code.
This also makes the user code bulky..
(I'm talking about removing all
timeouts parameters from everywhere)

Not removing leads to branches everywhere in
Curio code as you pointed out..

Both are bad.. But as a "user" I would like the latter
in optional timeout parameter form. Because
it makes "user" code much more elegant..

**Comment by njsmith** [comment] 2016-12-21 07:53
@imrn: The problem is that per-operation timeouts are almost never what you actually want. You usually want to impose timeouts on higher level actions like "this HTTP request" not "reading the next byte from this socket". So timeout parameters aren't very useful in practice, and involve a huge amount of extra code in curio, + extra code in all user APIs if the user API wants to follow the convention and implement a timeout parameter too. Better just to consistently leave it out and stick with the context manager approach.

**Comment by imrn** [comment] 2016-12-21 10:12
That's the way of "exceptions". It's bad style..

**Comment by dabeaz** [comment] 2016-12-26 21:28
Closing.  Has been fixed in github.  Use timeout_after() to use a timeout with the subprocess functions.

**Closed** 2016-12-26 21:28 UTC
