### ISSUE TITLE
Problem with ignore_after context manager?

### ISSUE THREAD

**Issue by ColMcp** [dabeaz/curio#52] opened 2016-05-23 14:33 UTC
I'm experimenting with a mixed tinter + curio example. Here is the curio section:

```
async def generate_messages(app, ctrl, gap):
    await app.running.wait()
    async with ignore_after(DURATION):
        while app.running.is_set():
            app._window.generate_message(ctrl)
            await sleep(gap)

async def tk_runloop(app):
    await app.running.wait()
    while app.running.is_set():
        app.update()
        await sleep(0.1)

async def main():
    app = Application('curio/Tk Example')
    app.update()

    rl = await spawn(tk_runloop(app))

    m0 = await spawn(generate_messages(app, 0, 0.05))
    m1 = await spawn(generate_messages(app, 1, 0.1))
    m2 = await spawn(generate_messages(app, 2, 0.2))
    m3 = await spawn(generate_messages(app, 3, 0.4))

    await app.running.set()

    await rl.join()

if __name__ == '__main__':
    k = Kernel(with_monitor=True)
    k.run(main())
    k.run(None, shutdown=True)
```

This almost always does what I expect: the GUI appears, the 4 `generate_messages()` tasks run, the GUI is updated, then after `DURATION` seconds the `generate_messages()` tasks exit.

Occasionally only 3 of the tasks exit; the other, always `m0`, just keeps on going. Using the monitor's `ps` command I can see the 4 tasks' Timeout values decreasing, then 3 tasks disappear while the other's timeout value becomes None and it carries on executing.

Have I misunderstood the purpose and working of `ignore_after()` used as a context manager or could this be a problem with curio?

[tkapp.zip](https://github.com/dabeaz/curio/files/277659/tkapp.zip)

**Comment by dabeaz** [comment] 2016-05-23 15:16
Interesting.   I'm looking at it now and have reproduced the problem on my machine.   More shortly (hopefully).

**Comment by dabeaz** [comment] 2016-05-23 16:00
I've pushed a change that should fix this.  In a nutshell: the task was waking from sleep and being cancelled by timeout at exactly the same time. Depending on the order of how those were processed, there was a chance that the timeout could simply be ignored.  I'm not able to reproduce the issue after the change so I'd say give it a try and let me know so I can close this.

**Comment by ColMcp** [comment] 2016-05-23 19:44
Your fix looks OK - I too cannot reproduce the problem using my original example or a similar one that used PyQt5 for the GUI.

Thank you!

**Comment by dabeaz** [comment] 2016-05-24 09:49
Great.  Thanks for the bug report!

**Closed by dabeaz** 2016-05-24 09:49 UTC
